import { Event, Category, EventStatus } from "@/components/events/types/events";

export const CLIP_PATH = "polygon(10px 0%, calc(100% - 10px) 0%, 100% 10px, calc(100% - 50px) 100%, 30px 100%, 0px 15px)";

export const IMAGE_CLIP_PATH = "polygon(40px 0%, 100% 0%, 100% calc(100% - 40px), calc(100% - 40px) 100%, 0% 100%, 0% 40px)";

export const CARD_DIMENSIONS = { w: 298, h: 418 };

export const CATEGORIES: Category[] = [
  "All",
  "Coding",
  "Circuits and Robotics",
  "Business",
  "Brainstroming",
  "Gaming",
  "Esports",
  "Specials1",
  "Specials2",
  "Specials3",
  "Specials4",
  "Specials5",
  "Specials6",
  "Specials7",
  "Specials8",
  "Specials9",
  "Misc",
];

export const STATUSES: EventStatus[] = ["All", "Open", "Closed", "Coming Soon"];

export const EVENTS_DATA: Event[] = [
  // --- CODING ---
  {
    id: "1",
    slug: "h42", 
    color: "#FF3429", 
    title: "H42",
    category: "Coding",
    description: "The flagship competitive programming contest. Battle against the best coders to solve complex algorithmic challenges.",
    format: "Online",
    rules: ["Individual participation", "HackerRank platform", "Plagiarism check enabled"],
    lastDate: "19th April",
    prizePool: "₹ 15,000",
    teamSize: "Individual",
    coordinators: [{ name: "Alice Dev", contact: "9988776655" }],
    link: "/register/h42",
    driveLink: "https://lorempdf.com/564/850/1",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["CP", "Algorithms", "Flagship"],
    status: "Open",
    prelimsDate: "15th April",
    finalsDate: "20th April",
    winnerPrize: "₹ 8,000",
    runnersUpPrize: "₹ 5,000",
    secondRunnersUpPrize: "₹ 2,000",
  },
  {
    id: "2",
    slug: "cypher-3301", 
    color: "#FA892E", 
    title: "Cypher 3301",
    category: "Coding",
    description: "A cryptography and puzzle-solving event. Decrypt the clues to advance to the next level.",
    format: "Online",
    rules: ["CTF Style", "Teams allowed"],
    lastDate: "18th April",
    prizePool: "₹ 8,000",
    teamSize: "1-2 Members",
    coordinators: [{ name: "Neo Matrix", contact: "9876543210" }],
    link: "/register/cypher",
    pdfLink: "https://lorempdf.com/420/595/2",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Crypto", "Puzzle", "Hacking"],
    status: "Open",
    prelimsDate: "16th April",
    finalsDate: "18th April",
    winnerPrize: "₹ 4,000",
    runnersUpPrize: "₹ 2,500",
    secondRunnersUpPrize: "₹ 1,500",
  },
  {
    id: "3",
    slug: "data-drift", 
    color: "#1CC1EB", 
    title: "Data Drift",
    category: "Coding",
    description: "A data science hackathon. Analyze the dataset, build models, and predict the outcome with the highest accuracy.",
    format: "Hybrid",
    rules: ["Kaggle submission", "Presentation required for finalists"],
    lastDate: "20th April",
    prizePool: "₹ 12,000",
    teamSize: "1-3 Members",
    coordinators: [{ name: "David Tensor", contact: "8899776655" }],
    link: "/register/data-drift",
    driveLink: "https://lorempdf.com/794/1123/3",
    image: "https://i.pinimg.com/736x/20/73/a2/2073a2ab4ddbb15c9e804fd4eb9c388e.jpg",
    tags: ["AI/ML", "Data Science"],
    status: "Coming Soon",
    prelimsDate: "17th April",
    finalsDate: "20th April",
  },
  {
    id: "4",
    slug: "web-weaver", 
    color: "#384DFF", 
    title: "Web Weaver",
    category: "Coding",
    description: "Frontend development challenge. Replicate a UI design or build a creative web app within a strict time limit.",
    format: "Offline",
    rules: ["No templates allowed", "Responsive design mandatory", "Vanilla JS or React"],
    lastDate: "19th April",
    prizePool: "₹ 6,000",
    teamSize: "Individual",
    coordinators: [{ name: "Sarah Styles", contact: "7766554433" }],
    link: "/register/web-weaver",
    pdfLink: "https://lorempdf.com/612/792/4",
    image: "https://i.pinimg.com/736x/c7/b3/46/c7b3464e077a74ec9369a54c03c99a3d.jpg",
    tags: ["Web Dev", "Design", "UI/UX"],
    status: "Closed",
    winnerPrize: "₹ 3,000",
    runnersUpPrize: "₹ 2,000",
  },

  // --- CIRCUITS AND ROBOTICS ---
  {
    id: "5",
    slug: "death-race", 
    color: "#D3EDFB", 
    title: "Death Race",
    category: "Circuits and Robotics",
    description: "Build a manual bot capable of traversing an extreme obstacle course filled with traps in minimum time.",
    format: "Offline",
    rules: ["Bot max dimensions: 30x30x30cm", "Wireless/Wired control allowed", "Max voltage 12V"],
    lastDate: "21st April",
    prizePool: "₹ 35,000",
    teamSize: "3-5 Members",
    coordinators: [{ name: "Jane Smith", contact: "9123456780" }],
    link: "/register/death-race",
    driveLink: "https://lorempdf.com/744/1052/5",
    image: "https://i.pinimg.com/736x/cb/8b/04/cb8b0463ee8acec4771cdf4ce523f795.jpg",
    tags: ["Robotics", "Racing", "Flagship"],
    status: "Open",
    prelimsDate: "19th April",
    finalsDate: "21st April",
    winnerPrize: "₹ 18,000",
    runnersUpPrize: "₹ 10,000",
    secondRunnersUpPrize: "₹ 7,000",
  },
  {
    id: "6",
    slug: "line-follower", 
    color: "#E05B78", 
    title: "Line Follower",
    category: "Circuits and Robotics",
    description: "Design an autonomous robot that can accurately follow a complex black line on a white surface.",
    format: "Offline",
    rules: ["Completely autonomous", "No external controllers"],
    lastDate: "20th April",
    prizePool: "₹ 15,000",
    teamSize: "1-4 Members",
    coordinators: [{ name: "Raj Mech", contact: "9988112233" }],
    link: "/register/lfr",
    pdfLink: "https://lorempdf.com/500/707/6",
    image: "https://i.pinimg.com/736x/bf/8c/3a/bf8c3a6c879a0e6f454cb3b5a9faa860.jpg",
    tags: ["Robotics", "Autonomous"],
    status: "Open",
    finalsDate: "20th April",
    winnerPrize: "₹ 8,000",
  },
  {
    id: "7",
    slug: "circuit-debugger", 
    color: "#1DDBFF", 
    title: "Circuit Debugger",
    category: "Circuits and Robotics",
    description: "Test your electronics knowledge by finding faults in breadboard setups and schematic diagrams.",
    format: "Offline",
    rules: ["Time-based evaluation", "Basic tools provided"],
    lastDate: "18th April",
    prizePool: "₹ 5,000",
    teamSize: "Individual",
    coordinators: [{ name: "Volt Hunter", contact: "8877665544" }],
    link: "/register/circuit",
    driveLink: "https://lorempdf.com/680/960/7",
    image: "https://i.pinimg.com/736x/2b/ed/c2/2bedc27dc71c6e3038df9b0682284553.jpg",
    tags: ["Electronics", "Hardware"],
    status: "Coming Soon",
  },

  // --- BUSINESS ---
  {
    id: "8",
    slug: "b-plan", 
    color: "#FBEC1D", 
    title: "B-Plan",
    category: "Business",
    description: "Pitch your startup idea to a panel of investors. Focus on market analysis, revenue models, and scalability.",
    format: "Offline",
    rules: ["10-minute pitch", "5-minute Q&A", "Prototypes encouraged"],
    lastDate: "15th April",
    prizePool: "₹ 25,000",
    teamSize: "2-4 Members",
    coordinators: [{ name: "Elon Musk", contact: "7788990011" }],
    link: "/register/bplan",
    pdfLink: "https://lorempdf.com/595/842/8",
    image: "https://i.pinimg.com/736x/47/82/fb/4782fb50545e369f6af2fce6c759a7f0.jpg",
    tags: ["Startup", "Pitch", "Entrepreneurship"],
    status: "Open",
    prelimsDate: "16th April",
    finalsDate: "19th April",
    winnerPrize: "₹ 15,000",
    runnersUpPrize: "₹ 10,000",
  },
  {
    id: "9",
    slug: "mock-stock", 
    color: "#E1F701", 
    title: "Mock Stock",
    category: "Business",
    description: "Experience the thrill of Dalal Street. Trade virtual stocks, react to news flashes, and build the highest portfolio value.",
    format: "Hybrid",
    rules: ["Initial capital provided", "Trading halts on major news"],
    lastDate: "", 
    prizePool: "₹ 10,000",
    teamSize: "1-2 Members",
    coordinators: [{ name: "Warren Buffett", contact: "9900112233" }],
    link: "/register/mockstock",
    driveLink: "https://lorempdf.com/460/650/9",
    image: "https://i.pinimg.com/1200x/2d/d8/ab/2dd8abae9f0796424613d4151351bb96.jpg",
    tags: ["Trading", "Finance"],
    status: "Open",
  },

  // --- BRAINSTORMING ---
  {
    id: "10",
    slug: "tech-debate", 
    color: "#A9FEFC", 
    title: "Tech Debate",
    category: "Brainstroming",
    description: "Debate on controversial and emerging technological topics like AI ethics, Web3 regulation, and tech monopolies.",
    format: "Offline",
    rules: ["Oxford style debate", "Topic given 15 mins prior"],
    lastDate: "17th April",
    prizePool: "₹ 4,000",
    teamSize: "Individual",
    coordinators: [{ name: "Socrates", contact: "6677889900" }],
    link: "/register/debate",
    pdfLink: "https://lorempdf.com/520/735/10",
    image: "https://i.pinimg.com/736x/d7/f7/b5/d7f7b53c2b3e552775435bc861b19331.jpg",
    tags: ["Speaking", "Tech", "Ethics"],
    status: "Coming Soon",
  },
  {
    id: "11",
    slug: "case-study", 
    color: "#EA423F", 
    title: "Case Study",
    category: "Brainstroming",
    description: "Analyze a real-world engineering or corporate failure and present a comprehensive solution and preventative strategy.",
    format: "Offline",
    rules: ["Slide deck mandatory", "Judged on practicality"],
    lastDate: "18th April",
    prizePool: "₹ 8,000",
    teamSize: "2-3 Members",
    coordinators: [{ name: "Consultant X", contact: "5544332211" }],
    link: "/register/casestudy",
    driveLink: "https://lorempdf.com/700/990/11",
    image: "https://i.pinimg.com/736x/8a/5b/31/8a5b31922c4fda97e7bf98a998888d7d.jpg",
    tags: ["Analysis", "Problem Solving"],
    status: "Open",
  },

  // --- ESPORTS ---
  {
    id: "12",
    slug: "valorant-tournament", 
    color: "#FC422D", 
    title: "Valorant Tournament",
    category: "Esports",
    description: "5v5 tactical shooter tournament. Prove your aim and strategy to claim the championship title.",
    format: "Online",
    rules: ["Knockout bracket", "Anti-cheat enforced", "Standard competitive map pool"],
    lastDate: "14th April",
    prizePool: "₹ 20,000",
    teamSize: "5 Members + 1 Sub",
    coordinators: [{ name: "Jett", contact: "1122334455" }],
    link: "/register/valorant",
    pdfLink: "https://lorempdf.com/612/864/12",
    image: "https://i.pinimg.com/736x/05/50/58/055058f58c6ad4490100cf18bf21b11e.jpg",
    tags: ["FPS", "Gaming", "Flagship"],
    status: "Closed",
    winnerPrize: "₹ 12,000",
    runnersUpPrize: "₹ 8,000",
  },
  {
    id: "13",
    slug: "bgmi-clash", 
    color: "#FE7A16", 
    title: "BGMI Clash",
    category: "Esports",
    description: "Mobile battle royale. Survive till the end in custom rooms against the best squads.",
    format: "Online",
    rules: ["Point system based on placement and kills", "Mobile only, no emulators"],
    lastDate: "15th April",
    prizePool: "₹ 15,000",
    teamSize: "4 Members",
    coordinators: [{ name: "Mortal", contact: "2233445566" }],
    link: "/register/bgmi",
    driveLink: "https://lorempdf.com/480/678/13",
    image: "https://i.pinimg.com/1200x/97/52/06/975206b29eab83f51e7a05bf10b0365e.jpg",
    tags: ["Mobile", "Battle Royale"],
    status: "Open",
    prelimsDate: "16th April",
    finalsDate: "18th April",
  },
  {
    id: "14",
    slug: "ea-fc-24", 
    color: "#B7BEC0", 
    title: "EA FC 24",
    category: "Esports",
    description: "1v1 football tournament on console. Show off your dribbling and tactical mastery.",
    format: "Offline",
    rules: ["6 min halves", "Standard club teams", "No custom formations"],
    lastDate: "18th April",
    prizePool: "₹ 5,000",
    teamSize: "Individual",
    coordinators: [{ name: "Messi", contact: "3344556677" }],
    link: "/register/eafc",
    pdfLink: "https://lorempdf.com/540/762/14",
    image: "https://i.pinimg.com/736x/ba/98/f7/ba98f7e127802bd1914fe8c3598a1788.jpg",
    tags: ["Sports", "Console"],
    status: "Coming Soon",
  },

  // --- GAMING (Casual/Board) ---
  {
    id: "15",
    slug: "chess-blitz", 
    color: "#E6C31D", 
    title: "Chess Blitz",
    category: "Gaming",
    description: "Fast-paced blitz chess tournament. Outsmart your opponent before the clock runs out.",
    format: "Offline",
    rules: ["3 min + 2 sec increment", "FIDE rules apply"],
    lastDate: "19th April",
    prizePool: "₹ 3,000",
    teamSize: "Individual",
    coordinators: [{ name: "Magnus", contact: "4455667788" }],
    link: "/register/chess",
    driveLink: "https://lorempdf.com/595/841/15",
    image: "https://i.pinimg.com/736x/71/6e/89/716e894781e4018eb42e54f349b52fdc.jpg",
    tags: ["Board Game", "Strategy"],
    status: "Open",
  },

  {
    id: "16",
    slug: "tech-expo", 
    color: "#FDFC34", 
    title: "Tech Expo",
    category: "Misc",
    description: "Exhibition of the latest projects, drones, and software created by students and industry professionals.",
    format: "Offline",
    rules: ["Open to all attendees", "No registration required for viewing"],
    lastDate: "", 
    prizePool: "N/A",
    teamSize: "N/A",
    coordinators: [{ name: "Expo Head", contact: "5566778899" }],
    link: "#",
    pdfLink: "https://lorempdf.com/720/1018/16",
    image: "https://i.pinimg.com/1200x/9d/e1/0a/9de10af30ffe2af573f0718386f41f4e.jpg",
    tags: ["Exhibition", "Innovation"],
    status: "Open",
    finalsDate: "19th - 21st April",
  },
  {
    id: "17",
    slug: "guest-lecture-ai-future", 
    color: "#EDCD48", 
    title: "Guest Lecture: AI Future",
    category: "Misc",
    description: "A keynote session by an industry veteran on the future of Generative AI and its impact on software engineering.",
    format: "Hybrid",
    rules: ["Seats on first-come-first-serve basis"],
    lastDate: "18th April",
    prizePool: "N/A",
    teamSize: "Individual",
    coordinators: [{ name: "Seminar PR", contact: "6677889900" }],
    link: "/register/lecture",
    driveLink: "https://lorempdf.com/640/904/17",
    image: "https://i.pinimg.com/1200x/ec/2a/f5/ec2af58ab96ba481cbbdbf4120da5de0.jpg",
    tags: ["Seminar", "AI", "Keynote"],
    status: "Closed",
  },

  // --- MISC ---
  {
    id: "18",
    slug: "rubiks-cube-relay", 
    color: "#E77374", 
    title: "Rubik's Cube Relay",
    category: "Misc",
    description: "Solve the 3x3 Rubik's cube as fast as possible in a team relay format.",
    format: "Offline",
    rules: ["Standard WCA inspection time", "Bring your own cube"],
    lastDate: "20th April",
    prizePool: "₹ 2,000",
    teamSize: "3 Members",
    coordinators: [{ name: "Speed Cuber", contact: "7788990011" }],
    link: "/register/cube",
    pdfLink: "https://lorempdf.com/560/792/18",
    image: "https://i.pinimg.com/736x/a4/fa/fc/a4fafc9fc031c43f4237a70d0d4ff83b.jpg",
    tags: ["Speedcubing", "Puzzle"],
    status: "Open",
  },
  {
    id: "19",
    slug: "math-olympiad", 
    color: "#D21C2D", 
    title: "Math Olympiad",
    category: "Misc",
    description: "Test your mathematical prowess with problems ranging from combinatorics to number theory.",
    format: "Offline",
    rules: ["No calculators", "Show all working steps"],
    lastDate: "17th April",
    prizePool: "₹ 4,000",
    teamSize: "Individual",
    coordinators: [{ name: "Euler", contact: "8899001122" }],
    link: "/register/math",
    driveLink: "https://lorempdf.com/490/693/19",
    image: "https://i.pinimg.com/736x/ae/aa/1b/aeaa1b655debdd6838122309ce79f02b.jpg",
    tags: ["Mathematics", "Logic"],
    status: "Coming Soon",
  },
  {
    id: "20",
    slug: "treasure-hunt", 
    color: "#FE0000", 
    title: "Treasure Hunt",
    category: "Misc",
    description: "Explore the campus by solving riddles and completing physical tasks to find the ultimate hidden treasure.",
    format: "Offline",
    rules: ["Campus bounds only", "Time limit: 2 hours"],
    lastDate: "21st April",
    prizePool: "₹ 10,000",
    teamSize: "4-5 Members",
    coordinators: [{ name: "Jack Sparrow", contact: "9900112233" }],
    link: "/register/hunt",
    pdfLink: "https://lorempdf.com/612/867/20",
    image: "https://i.pinimg.com/1200x/c8/9e/46/c89e469e6aa96a0df4e9c47e94f0c7be.jpg",
    tags: ["Fun", "Outdoor", "Teamwork"],
",
    format: "Offline",
    rules: ["Campus bounds only", "Time limit: 2 hours"],
    lastDate: "21st April",
    prizePool: "₹ 10,000",
    teamSize: "4-5 Members",
    coordinators: [{ name: "Jack Sparrow", contact: "9900112233" }],
    link: "/register/hunt",
    pdfLink: "https://lorempdf.com/612/867/20",
    image: "https://i.pinimg.com/1200x/c8/9e/46/c89e469e6aa96a0df4e9c47e94f0c7be.jpg",
    tags: ["Fun", "Outdoor", "Teamwork"],
    status: "Open",
  },
];