import { Category, Event, EventStatus } from "../types/events";

export const CLIP_PATH = "polygon(10px 0%, calc(100% - 10px) 0%, 100% 10px, calc(100% - 50px) 100%, 30px 100%, 0px 15px)";
export const IMAGE_CLIP_PATH = "polygon(40px 0%, 100% 0%, 100% calc(100% - 40px), calc(100% - 40px) 100%, 0% 100%, 0% 40px)";

export const CATEGORIES: Category[] = [
  "All",
  "Coding",
  "Circuits and Robotics",
  "Business",
  "Brainstorming",
  "Gaming",
  "Esports",
  "Special Attractions",
  "Misc",
];

export const STATUSES: EventStatus[] = ["All", "Open", "Closed", "Coming Soon"];

export const EVENTS_DATA: Event[] = [
  {
    id: "2",
    slug: "lotr",
    color: "#FA892E",
    title: "Lord of The Ring : Season 3",
    category: "Circuits and Robotics",
    description: "The pinnacle of robotic competition where engineering brilliance meets tactical mastery in the exhilarating Robo Sumo arena! With teams of 3 to 5 members, battle to completely displace the competition.",
    format: "Offline",
    rules: ["Wired and wireless categories", "Robo Sumo arena", "Elimination rounds"],
    lastDate: "TBA",
    prizePool: "₹ 12,000",
    teamSize: "3-5 Members",
    coordinators: [
      { name: "Tuhin Roy", contact: "7980143323" },
      { name: "Soham Saha", contact: "8918140410" },
      { name: "Arnab Karmakar", contact: "9883415630" }
    ],
    link: "/register/lotr",
    driveLink: "https://drive.google.com/file/d/1rs6bQLQ9EZp5mE693C1IvyK4bOv4EvuN/view?usp=sharing",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Robotics", "Sumo", "Tactical"],
    status: "Open",
  },
  {
    id: "4",
    slug: "traffiq",
    color: "#384DFF",
    title: "TraffIQ",
    category: "Circuits and Robotics",
    description: "An AI-based autonomous vehicle competition where teams develop the software brain of a self-driving car using real-time camera input. Your task is to design, train, and integrate a computer vision and control system.",
    format: "Offline",
    rules: ["AI-based vehicle", "Real-time camera input", "Computer vision", "No human intervention"],
    lastDate: "TBA",
    prizePool: "₹ 6,500",
    teamSize: "2-5 Members",
    coordinators: [
      { name: "Rhitambhar Choudhury", contact: "6289848840" },
      { name: "Aayush Konar", contact: "9972095077" }
    ],
    link: "/register/traffiq",
    driveLink: "https://drive.google.com/drive/folders/1w6ObIiuupOY-Mlh-vM0K8bcHmoNqpvIy?usp=sharing",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["AI", "Autonomous", "Vision"],
    status: "Open",
  },
  {
    id: "5",
    slug: "mathemagician",
    color: "#FBEC1D",
    title: "Math-E-Magician",
    category: "Brainstorming",
    description: "Showcase your ingenuity as you treat numbers like a strategic game and ideas as your winning moves. Team up, think fast, and challenge sharp young minds through multiple competitive levels.",
    format: "Hybrid",
    rules: ["Multiple levels", "Strategy and logic", "Mathematical puzzles"],
    lastDate: "TBA",
    prizePool: "₹ 6,000",
    teamSize: "2 Members",
    coordinators: [
      { name: "Sayan Das", contact: "9432646056" },
      { name: "Gourav Roy", contact: "6291497375" },
      { name: "Sayanaditya Das", contact: "7679500949" }
    ],
    link: "/register/mathemagician",
    driveLink: "https://drive.google.com/file/d/15yQbreiwKAD4K42ECZC6XOO2qT-Klaf2/view?usp=sharing",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Math", "Strategy", "Brainstorm"],
    status: "Open",
  },
  {
    id: "6",
    slug: "epoch",
    color: "#E05B78",
    title: "Epochalypse",
    category: "Coding",
    description: "Welcome to Epochalypse, where static numbers evolve into high-stakes battlegrounds. Your mission is to harness the full power of data – decoding the past through immersive visualization and conquering the future via intelligent simulations.",
    format: "Hybrid",
    rules: ["Data visualization", "Intelligent simulations", "3 members per team"],
    lastDate: "TBA",
    prizePool: "₹ 10,000",
    teamSize: "3 Members",
    coordinators: [
      { name: "Atmik Goswami", contact: "8910425255" },
      { name: "Asmit Deb", contact: "6290050401" }
    ],
    link: "/register/epoch",
    driveLink: "https://drive.google.com/file/d/1z0xX5WVTDhK1wkC3i5FxChVbZXf2TRUC/view?usp=sharing",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Data Science", "Simulation", "Analytics"],
    status: "Open",
  },
  {
    id: "7",
    slug: "h42",
    color: "#1DDBFF",
    title: "H42",
    category: "Coding",
    description: "An ICPC-style contest for teams of three, focused on solving algorithmic problems under time pressure. Challenges speed, logic, and coding skills, making it a must-attend for CP enthusiasts.",
    format: "Hybrid",
    rules: ["ICPC-style", "Time pressure", "Online prelims & offline finals"],
    lastDate: "TBA",
    prizePool: "₹ 10,000",
    teamSize: "1-3 Members",
    coordinators: [
      { name: "Irfan Habeeb Gazi", contact: "9007130066" },
      { name: "Daniyal Anis", contact: "9748850137" },
      { name: "Sayantan Biswas", contact: "9062334673" }
    ],
    link: "/register/h42",
    driveLink: "https://drive.google.com/file/d/1WOEO91mqBPM8umnUz-oItd_6SMpwZ3Qm/view?usp=sharing",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["CP", "Algorithms", "Logic"],
    status: "Open",
  },
  {
    id: "8",
    slug: "sherlocked",
    color: "#A9FEFC",
    title: "Sherlocked",
    category: "Coding",
    description: "A two-round sci-fi mystery solving CTF combining cryptography, computer science fundamentals and investigative reasoning within an immersive narrative framework.",
    format: "Hybrid",
    rules: ["Cryptography", "Mystery solving", "Narrative framework", "Team of 3"],
    lastDate: "TBA",
    prizePool: "₹ 6,000",
    teamSize: "3 Members",
    coordinators: [
      { name: "Subhayan Roy Chowdhury", contact: "6289955350" },
      { name: "Kaji Manirul Islam", contact: "7865060015" },
      { name: "Swarnendu Banerjee", contact: "9564027954" }
    ],
    link: "/register/sherlocked",
    driveLink: "https://drive.google.com/file/d/1F4J8PDFqJRPXe4cvHb8S1DwjTTqTDvk0/view?usp=sharing",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["CTF", "Security", "Mystery"],
    status: "Open",
  },
  {
    id: "9",
    slug: "cypher3331",
    color: "#FC422D",
    title: "Cypher 3331",
    category: "Brainstorming",
    description: "Participants will dive into an exciting journey of brainstorming, ciphering, and Cryptography. A short crash course will equip you with all the essentials to battle through 4 thrilling stages.",
    format: "Offline",
    rules: ["Cryptography crash course", "4 stages", "Team of 3"],
    lastDate: "TBA",
    prizePool: "₹ 6,000",
    teamSize: "3 Members",
    coordinators: [
      { name: "Supratim Chakraborty", contact: "9123378441" },
      { name: "Mayukh Roy", contact: "9038929699" },
      { name: "Sarin Sanyal", contact: "9432264022" }
    ],
    link: "/register/cypher3331",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Crypto", "Brainstorm", "Puzzle"],
    status: "Open",
  },
  {
    id: "10",
    slug: "ss3",
    color: "#FE7A16",
    title: "Snap Syntax 3.0",
    category: "Coding",
    description: "Test your memory-powered coding skills! Recreate stunning web designs using just HTML, CSS. One glimpse, two hours, and your ability to turn memory into reality.",
    format: "Offline",
    rules: ["Memory-based coding", "HTML/CSS only", "2-hour limit"],
    lastDate: "TBA",
    prizePool: "₹ 10,000",
    teamSize: "2-4 Members",
    coordinators: [
      { name: "Ayan Ghosh", contact: "8167002490" },
      { name: "Swapnaneel Ray", contact: "7980515334" },
      { name: "Anuska Nath", contact: "9330129467" }
    ],
    link: "/register/ss3",
    driveLink: "https://drive.google.com/file/d/1Py4J3qnGrU0SfUNiyPmlf8bXmlRw89vh/view?usp=drive_link",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Web", "Design", "Memory"],
    status: "Open",
  },
  {
    id: "11",
    slug: "indx",
    color: "#B7BEC0",
    title: "INDUSTRIX",
    category: "Business",
    description: "Industrix is not just a competition, but a dynamic simulation of the modern industrial world! Navigate through supply chain hurdles and market fluctuations to build your industrial empire.",
    format: "Offline",
    rules: ["Industrial simulation", "Supply chain management", "Dynamic market", "Team of 4"],
    lastDate: "TBA",
    prizePool: "₹ 10,000",
    teamSize: "4 Members",
    coordinators: [
      { name: "Samiksha Agarwal", contact: "70032 68352" }
    ],
    link: "/register/indx",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Business", "Simulation", "Strategy"],
    status: "Open",
  },
  {
    id: "12",
    slug: "sv1",
    color: "#E6C31D",
    title: "System Vanguard",
    category: "Coding",
    description: "Dive into the heart of defensive cybersecurity! Your mission is to secure vulnerabilities, harden systems, and defend against simulated attacks in this high-intensity security challenge.",
    format: "Offline",
    rules: ["System hardening", "Defensive security", "Simulated attacks", "Team of 3"],
    lastDate: "TBA",
    prizePool: "₹ 7,500",
    teamSize: "3 Members",
    coordinators: [
      { name: "Subhranil", contact: "83348 37709" },
      { name: "Priyanshu", contact: "87884 94747" },
      { name: "Sourit", contact: "86177 56641" }
    ],
    link: "/register/sv1",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Security", "Cyber", "Defense"],
    status: "Open",
  },
  {
    id: "13",
    slug: "death_race",
    color: "#FDFC34",
    title: "Death Race",
    category: "Circuits and Robotics",
    description: "Gear up for the ultimate test of speed and durability! Guide your custom-built robot through a treacherous track filled with obstacles, jumps, and traps to claim the title of the fastest runner.",
    format: "Offline",
    rules: ["Custom-built robots", "Treacherous track", "Obstacles and jumps", "Team of 1-4"],
    lastDate: "TBA",
    prizePool: "₹ 15,500",
    teamSize: "1-4 Members",
    coordinators: [
      { name: "Avik", contact: "85098 70295" },
      { name: "Dibyendu", contact: "96357 56832" },
      { name: "Abhishek", contact: "98305 19280" }
    ],
    link: "/register/death_race",
    driveLink: "https://drive.google.com/drive/folders/1w6ObIiuupOY-Mlh-vM0K8bcHmoNqpvIy?usp=sharing",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Racing", "Robotics", "Obstacles"],
    status: "Open",
  },
  {
    id: "14",
    slug: "CC",
    color: "#EDCD48",
    title: "CONTROL-CRAFT",
    category: "Circuits and Robotics",
    description: "Master the art of feedback and control! Design and implement a controller to stabilize a complex dynamic system under varying disturbance conditions.",
    format: "Offline",
    rules: ["Control system design", "Feedback loops", "Dynamic stabilization", "Team of 4"],
    lastDate: "TBA",
    prizePool: "₹ 11,000",
    teamSize: "4 Members",
    coordinators: [
      { name: "Soumen", contact: "85098 70295" }
    ],
    link: "/register/CC",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Control", "Systems", "Design"],
    status: "Open",
  },
  {
    id: "15",
    slug: "RR",
    color: "#E77374",
    title: "ROPE RUNNER",
    category: "Circuits and Robotics",
    description: "Engineering meets agility! Build a robot capable of traversing a suspended rope-way with precision, speed, and balance.",
    format: "Offline",
    rules: ["Rope-way traversal", "Precision and balance", "Speed test", "Team of 4"],
    lastDate: "TBA",
    prizePool: "₹ 8,500",
    teamSize: "4 Members",
    coordinators: [
      { name: "Animesh", contact: "85098 70295" }
    ],
    link: "/register/RR",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Robotics", "Rope-way", "Engineering"],
    status: "Open",
  },
  {
    id: "16",
    slug: "btg26",
    color: "#D21C2D",
    title: "Bridge The Gap",
    category: "Misc",
    description: "A civil engineering marvel! Construct a miniature bridge using limited materials that can withstand incredible loads. Your design will be tested to the point of failure.",
    format: "Offline",
    rules: ["Limited materials", "Load bearing test", "Structural integrity", "Team of 2-4"],
    lastDate: "TBA",
    prizePool: "₹ 10,000",
    teamSize: "2-4 Members",
    coordinators: [
      { name: "Deepak", contact: "85098 70295" }
    ],
    link: "/register/btg26",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Civil", "Bridge", "Structural"],
    status: "Open",
  },
  {
    id: "17",
    slug: "caseomania",
    color: "#FE0000",
    title: "CASE O MANIA",
    category: "Brainstorming",
    description: "Analyze, strategize, and solve! Tackle real-world corporate dilemmas and propose viable solutions in this intense business case study competition.",
    format: "Offline",
    rules: ["Case study analysis", "Strategic solution", "Presentation round", "Team of 2-3"],
    lastDate: "TBA",
    prizePool: "₹ 8,000",
    teamSize: "2-3 Members",
    coordinators: [
      { name: "Rishav", contact: "85098 70295" }
    ],
    link: "/register/caseomania",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Business", "Case Study", "Analysis"],
    status: "Open",
  },
  {
    id: "18",
    slug: "ptb",
    color: "#FF3429",
    title: "Pass the Baton",
    category: "Coding",
    description: "Coding as a relay race! Teams must work in sequence to solve a multi-stage problem, where each member inherits the code of their predecessor. Synchronization is key.",
    format: "Offline",
    rules: ["Relay format", "Sequential coding", "Synchronization", "Team of 3"],
    lastDate: "TBA",
    prizePool: "₹ 8,500",
    teamSize: "3 Members",
    coordinators: [
      { name: "Sourav", contact: "85098 70295" }
    ],
    link: "/register/ptb",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Coding", "Relay", "Teamwork"],
    status: "Open",
  },
  {
    id: "19",
    slug: "XSTREAM",
    color: "#FA892E",
    title: "XSTERAM",
    category: "Circuits and Robotics",
    description: "Push the limits of aerodynamics and propulsion! Build a high-speed vehicle designed to excel in straight-line acceleration and drag efficiency.",
    format: "Offline",
    rules: ["Aerodynamic design", "High-speed acceleration", "Straight-line track", "Team of 1-4"],
    lastDate: "TBA",
    prizePool: "₹ 14,000",
    teamSize: "1-4 Members",
    coordinators: [
      { name: "Rahul", contact: "85098 70295" }
    ],
    link: "/register/XSTREAM",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Aerodynamics", "Racing", "Speed"],
    status: "Open",
  },
  {
    id: "20",
    slug: "h4g",
    color: "#1CC1EB",
    title: "HackForge",
    category: "Coding",
    description: "Forge your ideas into reality! A 24-hour hackathon where you build innovative software solutions from scratch. Innovation, scalability, and code quality are paramount.",
    format: "Offline",
    rules: ["24-hour hackathon", "Innovation based", "Scalability focused", "Team of 4"],
    lastDate: "TBA",
    prizePool: "₹ 20,000",
    teamSize: "4 Members",
    coordinators: [
      { name: "Priyanjali", contact: "85098 70295" }
    ],
    link: "/register/h4g",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Hackathon", "Coding", "Innovation"],
    status: "Open",
  },
  {
    id: "21",
    slug: "uncode",
    color: "#384DFF",
    title: "Uncode",
    category: "Coding",
    description: "The ultimate survival of the quickest! Compete in this high-intensity, multi-round elimination contest where clear logic and rapid execution are your only weapons.",
    format: "Offline",
    rules: ["Elimination contest", "Logic and speed", "Multi-round", "Team of 1-2"],
    lastDate: "TBA",
    prizePool: "₹ 5,000",
    teamSize: "1-2 Members",
    coordinators: [
      { name: "Ankana", contact: "85098 70295" }
    ],
    link: "/register/uncode",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Coding", "Survival", "Speed"],
    status: "Open",
  },
  {
    id: "22",
    slug: "arena-valorant",
    color: "#FBEC1D",
    title: "NSG ARENA x VALORANT",
    category: "Esports",
    description: "The premier Valorant showdown! Secure your tactical advantage and outplay your opponents in this elite 5v5 shooter tournament.",
    format: "Online",
    rules: ["Tactical 5v5", "Standard maps", "Competitive rules", "Team of 5"],
    lastDate: "TBA",
    prizePool: "₹ 15,000",
    teamSize: "5 Members",
    coordinators: [
      { name: "Swapnodeep", contact: "85098 70295" }
    ],
    link: "/register/arena-valorant",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Esports", "Valorant", "Tactical"],
    status: "Open",
  },
  {
    id: "23",
    slug: "arena-eafc",
    color: "#E05B78",
    title: "NSG ARENA x EAFC",
    category: "Esports",
    description: "Virtual football at its finest! Showcase your skills on the digital pitch and dominate the competition in this intense EAFC tournament.",
    format: "Offline",
    rules: ["Standard halves", "Console play", "Competitive brackets", "Individual"],
    lastDate: "TBA",
    prizePool: "₹ 5,000",
    teamSize: "Individual",
    coordinators: [
      { name: "Debarka", contact: "85098 70295" }
    ],
    link: "/register/arena-eafc",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Esports", "Football", "EAFC"],
    status: "Open",
  },
  {
    id: "24",
    slug: "openaimer",
    color: "#1DDBFF",
    title: "OpenAImer",
    category: "Coding",
    description: "Unleash the power of AI! Develop and deploy machine learning models to solve complex real-world challenges in this cutting-edge artificial intelligence competition.",
    format: "Hybrid",
    rules: ["Artificial Intelligence", "Model deployment", "Innovation focused", "Team of 1-4"],
    lastDate: "TBA",
    prizePool: "₹ 10,000",
    teamSize: "1-4 Members",
    coordinators: [
      { name: "Ritam", contact: "85098 70295" }
    ],
    link: "/register/openaimer",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["AI", "ML", "Data"],
    status: "Open",
  },
  {
    id: "26",
    slug: "arena-bgmi",
    color: "#FC422D",
    title: "NSG ARENA x BGMI",
    category: "Esports",
    description: "The ultimate battle royale! Drop into the Arena and outlast the rest in this high-stakes BGMI tournament where survival is the only objective.",
    format: "Online",
    rules: ["Battle Royale", "Squad play", "Competitive points", "Team of 4"],
    lastDate: "TBA",
    prizePool: "₹ 15,000",
    teamSize: "4 Members",
    coordinators: [
      { name: "Swapnodeep", contact: "85098 70295" }
    ],
    link: "/register/arena-bgmi",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Esports", "BGMI", "Survival"],
    status: "Open",
  },
  {
    id: "27",
    slug: "cr",
    color: "#FE7A16",
    title: "CLASH ROYALE",
    category: "Esports",
    description: "Master the Arena! Deploy your deck with precision and out-strategize your opponent in this intense Clash Royale 1v1 tournament.",
    format: "Online",
    rules: ["1v1 Duel", "Standard deck rotation", "Bracket play", "Individual"],
    lastDate: "TBA",
    prizePool: "₹ 3,500",
    teamSize: "Individual",
    coordinators: [
      { name: "Debarka", contact: "85098 70295" }
    ],
    link: "/register/cr",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Esports", "Mobile", "Strategy"],
    status: "Open",
  },
  {
    id: "29",
    slug: "uec-valorant",
    color: "#E6C31D",
    title: "NSG UEC x VALORANT",
    category: "Esports",
    description: "The Ultimate Esports Championship Valorant edition! Battle for glory and claim your spot among the legends in this high-tier tournament.",
    format: "Online",
    rules: ["Elite competition", "Standard tactical shooter", "Team of 5"],
    lastDate: "TBA",
    prizePool: "₹ 15,000",
    teamSize: "5 Members",
    coordinators: [
      { name: "Kushankur", contact: "85098 70295" }
    ],
    link: "/register/uec-valorant",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Esports", "Championship", "Valorant"],
    status: "Open",
  },
  {
    id: "30",
    slug: "uec-bgmi",
    color: "#FDFC34",
    title: "NSG UEC x BGMI",
    category: "Esports",
    description: "Survival of the fittest at the highest level! The UEC BGMI tournament brings together the best squads for an epic battle for supremacy.",
    format: "Online",
    rules: ["Battle Royale", "Squad play", "Championship level", "Team of 4"],
    lastDate: "TBA",
    prizePool: "₹ 15,000",
    teamSize: "4 Members",
    coordinators: [
      { name: "Kushankur", contact: "85098 70295" }
    ],
    link: "/register/uec-bgmi",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Esports", "BGMI", "Survival"],
    status: "Open",
  },
  {
    id: "31",
    slug: "uec-eafc",
    color: "#EDCD48",
    title: "NSG UEC x EAFC",
    category: "Esports",
    description: "Digital football at the peak of competition! Compete in the UEC EAFC tournament and prove you have what it takes to be the best.",
    format: "Offline",
    rules: ["Elite level", "Console play", "Competitive halves", "Individual"],
    lastDate: "TBA",
    prizePool: "₹ 5,000",
    teamSize: "Individual",
    coordinators: [
      { name: "Kushankur", contact: "85098 70295" }
    ],
    link: "/register/uec-eafc",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Esports", "Championship", "EAFC"],
    status: "Open",
  },
  {
    id: "32",
    slug: "uec-wtec",
    color: "#E77374",
    title: "NSG UEC x WTEC",
    category: "Esports",
    description: "Witness the clash of tech titans! Higher level competition in WTEC, where only the strongest skills survive.",
    format: "Online",
    rules: ["High-level competition", "WTEC rules", "Elite brackets", "Individual"],
    lastDate: "TBA",
    prizePool: "₹ 5,000",
    teamSize: "Individual",
    coordinators: [
      { name: "Kushankur", contact: "85098 70295" }
    ],
    link: "/register/uec-wtec",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Esports", "WTEC", "Elite"],
    status: "Open",
  },
  {
    id: "33",
    slug: "vrexp",
    color: "#D21C2D",
    title: "VR EXPERIENCE ZONE",
    category: "Gaming",
    description: "Step into the future of entertainment! Immerse yourself in breathtaking virtual worlds and interactive experiences in our dedicated VR Zone.",
    format: "Offline",
    rules: ["Time-limited sessions", "Open to all", "Safety guidelines apply", "Individual"],
    lastDate: "TBA",
    prizePool: "N/A",
    teamSize: "Individual",
    coordinators: [
      { name: "Aditya", contact: "85098 70295" }
    ],
    link: "/register/vrexp",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["VR", "Immersive", "Gaming"],
    status: "Open",
  },
  {
    id: "34",
    slug: "thunderbolts_voltedged",
    color: "#FE0000",
    title: "THUNDERBOLTS VOLTEDGED",
    category: "Circuits and Robotics",
    description: "High-voltage action! Design and build a combat robot to compete in this electrifying arena of destruction and strategy.",
    format: "Offline",
    rules: ["Weight categories", "Safety inspection", "Arena combat", "Team of 3-4"],
    lastDate: "TBA",
    prizePool: "₹ 15,000",
    teamSize: "3-4 Members",
    coordinators: [
      { name: "Rounak", contact: "85098 70295" }
    ],
    link: "/register/thunderbolts_voltedged",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Combat", "Electricity", "Robotics"],
    status: "Open",
  },
  {
    id: "35",
    slug: "datadrift26",
    color: "#FF3429",
    title: "Data Drift",
    category: "Coding",
    description: "Navigate through the ocean of data! Clean, analyze, and visualize complex datasets to uncover hidden patterns and provide data-driven insights.",
    format: "Hybrid",
    rules: ["Data cleaning", "Analysis accuracy", "Visualization quality", "Team of 1-2"],
    lastDate: "TBA",
    prizePool: "₹ 8,000",
    teamSize: "1-2 Members",
    coordinators: [
      { name: "Shrestha", contact: "85098 70295" }
    ],
    link: "/register/datadrift26",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Data", "Analytics", "Coding"],
    status: "Open",
  },
  {
    id: "36",
    slug: "ace-the-case",
    color: "#FA892E",
    title: "Ace The Case",
    category: "Business",
    description: "The ultimate business challenge! Outperform the competition in this multi-round strategic management and case solving event.",
    format: "Offline",
    rules: ["Strategic management", "Round-based evaluation", "Pitching finals", "Team of 2-4"],
    lastDate: "TBA",
    prizePool: "₹ 10,000",
    teamSize: "2-4 Members",
    coordinators: [
      { name: "Arya", contact: "85098 70295" }
    ],
    link: "/register/ace-the-case",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Business", "Strategy", "Management"],
    status: "Open",
  },
  {
    id: "37",
    slug: "biznez-plan",
    color: "#1CC1EB",
    title: "Biznez Plan",
    category: "Business",
    description: "Transform your vision into a viable business! Pitch your startup idea and detailed business model to a panel of expert judges and potential investors.",
    format: "Offline",
    rules: ["Startup pitch", "Business modeling", "Market analysis", "Team of 2-4"],
    lastDate: "TBA",
    prizePool: "₹ 12,000",
    teamSize: "2-4 Members",
    coordinators: [
      { name: "Akasdeep", contact: "85098 70295" }
    ],
    link: "/register/biznez-plan",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Entrepreneurship", "Business", "Pitch"],
    status: "Open",
  },
  {
    id: "38",
    slug: "stratedgex",
    color: "#384DFF",
    title: "StratEdgeX",
    category: "Business",
    description: "Gain the strategic edge! Navigate through complex business scenarios and competitive market conditions in this high-level strategy simulation.",
    format: "Offline",
    rules: ["Strategy simulation", "Decision making", "Market analysis", "Team of 1-4"],
    lastDate: "TBA",
    prizePool: "₹ 8,500",
    teamSize: "1-4 Members",
    coordinators: [
      { name: "Akasdeep", contact: "85098 70295" }
    ],
    link: "/register/stratedgex",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Strategy", "Business", "Simulation"],
    status: "Open",
  },
  {
    id: "39",
    slug: "pkv",
    color: "#FBEC1D",
    title: "Pack-o-vation",
    category: "Business",
    description: "Innovation in the box! Design and prototype innovative packaging solutions that are sustainable, efficient, and visually compelling.",
    format: "Offline",
    rules: ["Packaging design", "Sustainability focus", "Prototype mandatory", "Team of 2-4"],
    lastDate: "TBA",
    prizePool: "₹ 8,000",
    teamSize: "2-4 Members",
    coordinators: [
      { name: "Ayush", contact: "85098 70295" }
    ],
    link: "/register/pkv",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Sustainable", "Design", "Innovation"],
    status: "Open",
  },
  {
    id: "40",
    slug: "sks",
    color: "#E05B78",
    title: "SKYSPRINT",
    category: "Circuits and Robotics",
    description: "Aerodynamic excellence! Compete in this glider design and flight duration challenge to claim the title of the longest flight.",
    format: "Offline",
    rules: ["Glider design", "Stability and duration", "Limited materials", "Team of 2-3"],
    lastDate: "TBA",
    prizePool: "₹ 7,000",
    teamSize: "2-3 Members",
    coordinators: [
      { name: "Sayan", contact: "85098 70295" }
    ],
    link: "/register/sks",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Aero", "Glider", "Physics"],
    status: "Open",
  },
  {
    id: "41",
    slug: "clo",
    color: "#1DDBFF",
    title: "Climb On",
    category: "Misc",
    description: "A test of physical and mental endurance! Tackle the climbing challenge and reach peak efficiency in this athletic engineering event.",
    format: "Offline",
    rules: ["Safety harnesses", "Time-based climb", "Technical technique", "Individual"],
    lastDate: "TBA",
    prizePool: "₹ 4,000",
    teamSize: "Individual",
    coordinators: [
      { name: "Sarthak", contact: "85098 70295" }
    ],
    link: "/register/clo",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Endurance", "Sports", "Challenge"],
    status: "Open",
  },
  {
    id: "42",
    slug: "jal",
    color: "#A9FEFC",
    title: "Jal Astra",
    category: "Circuits and Robotics",
    description: "Launch into the splash zone! Design and launch a water-powered rocket, optimized for maximum range and stability.",
    format: "Offline",
    rules: ["Water rocket design", "Maximum range", "Stability control", "Team of 2-3"],
    lastDate: "TBA",
    prizePool: "₹ 7,500",
    teamSize: "2-3 Members",
    coordinators: [
      { name: "Swarnava", contact: "85098 70295" }
    ],
    link: "/register/jal",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Rocketry", "Physics", "Mechanics"],
    status: "Open",
  },
  {
    id: "43",
    slug: "hcg",
    color: "#FC422D",
    title: "Homecoming",
    category: "Circuits and Robotics",
    description: "The robotic rescue mission! Develop a robot capable of navigating a complex environment to locate and safely retrieve essential objects.",
    format: "Offline",
    rules: ["Autonomous navigation", "Object retrieval", "Time efficiency", "Team of 4-5"],
    lastDate: "TBA",
    prizePool: "₹ 18,000",
    teamSize: "4-5 Members",
    coordinators: [
      { name: "Suman", contact: "85098 70295" }
    ],
    link: "/register/hcg",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Robotics", "Rescue", "Navigation"],
    status: "Open",
  },
  {
    id: "44",
    slug: "rbs",
    color: "#FE7A16",
    title: "Robosoccer",
    category: "Circuits and Robotics",
    description: "The beautiful game, roboticized! Compete in this high-intensity robot football tournament where speed and precision goals win the match.",
    format: "Offline",
    rules: ["Remote control bots", "Football tactics", "Standard time", "Team of 3-5"],
    lastDate: "TBA",
    prizePool: "₹ 15,000",
    teamSize: "3-5 Members",
    coordinators: [
      { name: "Sourya", contact: "85098 70295" }
    ],
    link: "/register/rbs",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Robotics", "Football", "Strategy"],
    status: "Open",
  },
  {
    id: "45",
    slug: "capitalclash",
    color: "#B7BEC0",
    title: "CAPITAL CLASH",
    category: "Business",
    description: "Finance masters showdown! Test your knowledge of investment, capital markets, and financial management in this intense final clash.",
    format: "Offline",
    rules: ["Financial analysis", "Investment modeling", "Quiz and Case", "Team of 3"],
    lastDate: "TBA",
    prizePool: "₹ 8,000",
    teamSize: "3 Members",
    coordinators: [
      { name: "Swarnima", contact: "85098 70295" }
    ],
    link: "/register/capitalclash",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Finance", "Capital", "Business"],
    status: "Open",
  },
  {
    id: "46",
    slug: "er",
    color: "#E6C31D",
    title: "Escape Room",
    category: "Brainstorming",
    description: "Locked in a world of riddles! Solve complex puzzles and follow the clues to secure your escape before the time runs out.",
    format: "Offline",
    rules: ["Time-limited escape", "Logical puzzles", "Team puzzle-solving", "Team of 3-4"],
    lastDate: "TBA",
    prizePool: "₹ 5,000",
    teamSize: "3-4 Members",
    coordinators: [
      { name: "Vanshika", contact: "85098 70295" }
    ],
    link: "/register/er",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Puzzles", "Logic", "Fun"],
    status: "Open",
  },
  {
    id: "47",
    slug: "h2h",
    color: "#FDFC34",
    title: "Highway to Hell",
    category: "Circuits and Robotics",
    description: "The ultimate endurance race! Guide your robot through a high-speed, high-stress track designed to test the limits of your engineering.",
    format: "Offline",
    rules: ["Endurance track", "High-speed components", "Minimal repairs allowed", "Team of 3-5"],
    lastDate: "TBA",
    prizePool: "₹ 14,000",
    teamSize: "3-5 Members",
    coordinators: [
      { name: "Purnesh", contact: "85098 70295" }
    ],
    link: "/register/h2h",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Endurance", "Racing", "Robotics"],
    status: "Open",
  },
  {
    id: "48",
    slug: "justdefy",
    color: "#EDCD48",
    title: "Just Defy",
    category: "Brainstorming",
    description: "Battle of words and wit! Defy conventional logic and win the argument in this multi-round debating and critical thinking event.",
    format: "Offline",
    rules: ["Debating format", "Critical thinking", "Logic based", "Individual"],
    lastDate: "TBA",
    prizePool: "₹ 3,500",
    teamSize: "Individual",
    coordinators: [
      { name: "Oishani", contact: "85098 70295" }
    ],
    link: "/register/justdefy",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Debate", "Logic", "Speech"],
    status: "Open",
  },
  {
    id: "49",
    slug: "btm",
    color: "#E77374",
    title: "Beat the Market",
    category: "Business",
    description: "Show off your financial prowess! Navigate the stock market, manage your portfolio, and outperform the index in this realistic trading simulation.",
    format: "Offline",
    rules: ["Trading simulation", "Portfolio management", "Market fluctuations", "Individual"],
    lastDate: "TBA",
    prizePool: "₹ 5,000",
    teamSize: "Individual",
    coordinators: [
      { name: "Shrestha", contact: "85098 70295" }
    ],
    link: "/register/btm",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["Finance", "Trading", "Business"],
    status: "Open",
  },
  {
    id: "50",
    slug: "cc",
    color: "#D21C2D",
    title: "Cold Case",
    category: "Brainstorming",
    description: "The investigator's challenge! Solve a complex unsolved mystery by analyzing evidence, follow the trail of clues, and catch the culprit.",
    format: "Offline",
    rules: ["Evidence analysis", "Deductive reasoning", "Time-based solving", "Individual"],
    lastDate: "TBA",
    prizePool: "₹ 4,000",
    teamSize: "Individual",
    coordinators: [
      { name: "Debal", contact: "85098 70295" }
    ],
    link: "/register/cc",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Mystery", "Logic", "Investigation"],
    status: "Open",
  },
  {
    id: "51",
    slug: "iotbw",
    color: "#FE0000",
    title: "IoT BIDWARS",
    category: "Circuits and Robotics",
    description: "Bid for your tech future! Secure essential IoT components in a tactical auction and build the most innovative smart solution under budget.",
    format: "Offline",
    rules: ["Tactical auction", "IoT component focus", "Functional prototype", "Team of 2-3"],
    lastDate: "TBA",
    prizePool: "₹ 9,000",
    teamSize: "2-3 Members",
    coordinators: [
      { name: "Kushankur", contact: "85098 70295" }
    ],
    link: "/register/iotbw",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/c9/1a/e0/c91ae028da18f1302c1ee5406b5fd9b7.jpg",
    tags: ["IoT", "Auction", "Innovation"],
    status: "Open",
  },
  {
    id: "52",
    slug: "djk",
    color: "#FF3429",
    title: "DANK JUNK",
    category: "Misc",
    description: "The ultimate meme-making showdown! Create the most viral, hilarious, and relevant engineering memes to claim the title of the Meme Lord.",
    format: "Online",
    rules: ["Original content only", "Viral potential", "Engineering relevancy", "Individual"],
    lastDate: "TBA",
    prizePool: "₹ 2,000",
    teamSize: "Individual",
    coordinators: [
      { name: "Driptesh", contact: "85098 70295" }
    ],
    link: "/register/djk",
    driveLink: "#",
    image: "https://i.pinimg.com/736x/a4/82/6d/a4826d889c0d73a87106e19bf8c00b2a.jpg",
    tags: ["Memes", "Creative", "Viral"],
    status: "Open",
  },
];